[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "scripts"
solc = "0.8.26"
optimizer = true
optimizer_runs = 1
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@interfaces/=interfaces/",
    "@contracts/=contracts/",
    "@libraries/=libraries/"
]

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true

[rpc_endpoints]
base = "${BASE_RPC_URL}"